### ISSUE TITLE
书籍配套资料.zip 檔案損壞

### ISSUE THREAD

**Issue by b09780978** [riusksk/vul_war#1]
買了書，下載书籍配套资料.zip，解壓縮顯示檔案損壞，百度雲連結也失效。

**Comment by riusksk** [comment]
要么你确实下载不完整，要么就是解压软件有问题，换一款就好了

**Comment by b09780978** [comment]
已解決，用git clone抓下來的书籍配套资料.zip永遠只有1kb，要直接下載书籍配套资料.zip才沒問題。
