### ISSUE TITLE
配套资料解压提示文件损坏

### ISSUE THREAD

**Issue by voidException** [riusksk/vul_war#3]
解压里面的文件时，提示格式损坏，作者能再次上传一次吗

**Comment by voidException** [comment]
百度云的也无法下载了

**Comment by riusksk** [comment]
> 解压里面的文件时，提示格式损坏，作者能再次上传一次吗

应该是你下载不完整，git 无法下载的话，可以试试迅雷

**Comment by riusksk** [comment]
下载命令： git lfs clone xxx
