### ISSUE TITLE
Can't download source code

### ISSUE THREAD

**Issue by my-star** [riusksk/vul_war#4]
无法下载vul_war 资源文件，请帮忙解决一下

**Comment by riusksk** [comment]
测试下载正常，你可以直接下载压缩包：
https://github.com/riusksk/vul_war/raw/master/%E4%B9%A6%E7%B1%8D%E9%85%8D%E5%A5%97%E8%B5%84%E6%96%99.zip?download=

**Comment by my-star** [comment]
已通过回复中的链接下载完成，谢谢大佬。还发现百度网盘的链接被封了
